version: 2.1
workflows:
  version: 2
  # deploy: 
  #   jobs: 
  #   - pantheon/push:
  #     filters:
  #       branches:
  #         only:
  #         - master
  just_push:
      jobs:
      - pantheon/push:
        filters:
          branches:
            only:
            - master
orbs:
  pantheon: pantheon-systems/pantheon@0.6.0